version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Assa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  assa.test.backend:
    image: ${DOCKER_REGISTRY-}assatestbackend
    build:
      context: .
      dockerfile: Assa.Test.Backend/Dockerfile
    environment:
      ConnectionStrings__Assa: "Host=postgres;Port=5432;Database=Assa;User Id=postgres;Password=root;"
    ports:
      - "5250:80"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
